// Code generated by protoc-gen-go. DO NOT EDIT.
// source: greet/greetpb/greet.proto

package greetpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Greeting struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Greeting) Reset()         { *m = Greeting{} }
func (m *Greeting) String() string { return proto.CompactTextString(m) }
func (*Greeting) ProtoMessage()    {}
func (*Greeting) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{0}
}

func (m *Greeting) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Greeting.Unmarshal(m, b)
}
func (m *Greeting) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Greeting.Marshal(b, m, deterministic)
}
func (m *Greeting) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Greeting.Merge(m, src)
}
func (m *Greeting) XXX_Size() int {
	return xxx_messageInfo_Greeting.Size(m)
}
func (m *Greeting) XXX_DiscardUnknown() {
	xxx_messageInfo_Greeting.DiscardUnknown(m)
}

var xxx_messageInfo_Greeting proto.InternalMessageInfo

func (m *Greeting) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *Greeting) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

type GreetReq struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetReq) Reset()         { *m = GreetReq{} }
func (m *GreetReq) String() string { return proto.CompactTextString(m) }
func (*GreetReq) ProtoMessage()    {}
func (*GreetReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{1}
}

func (m *GreetReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetReq.Unmarshal(m, b)
}
func (m *GreetReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetReq.Marshal(b, m, deterministic)
}
func (m *GreetReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetReq.Merge(m, src)
}
func (m *GreetReq) XXX_Size() int {
	return xxx_messageInfo_GreetReq.Size(m)
}
func (m *GreetReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetReq.DiscardUnknown(m)
}

var xxx_messageInfo_GreetReq proto.InternalMessageInfo

func (m *GreetReq) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetRes struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetRes) Reset()         { *m = GreetRes{} }
func (m *GreetRes) String() string { return proto.CompactTextString(m) }
func (*GreetRes) ProtoMessage()    {}
func (*GreetRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{2}
}

func (m *GreetRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetRes.Unmarshal(m, b)
}
func (m *GreetRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetRes.Marshal(b, m, deterministic)
}
func (m *GreetRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetRes.Merge(m, src)
}
func (m *GreetRes) XXX_Size() int {
	return xxx_messageInfo_GreetRes.Size(m)
}
func (m *GreetRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetRes.DiscardUnknown(m)
}

var xxx_messageInfo_GreetRes proto.InternalMessageInfo

func (m *GreetRes) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetManyReq struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetManyReq) Reset()         { *m = GreetManyReq{} }
func (m *GreetManyReq) String() string { return proto.CompactTextString(m) }
func (*GreetManyReq) ProtoMessage()    {}
func (*GreetManyReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{3}
}

func (m *GreetManyReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyReq.Unmarshal(m, b)
}
func (m *GreetManyReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyReq.Marshal(b, m, deterministic)
}
func (m *GreetManyReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyReq.Merge(m, src)
}
func (m *GreetManyReq) XXX_Size() int {
	return xxx_messageInfo_GreetManyReq.Size(m)
}
func (m *GreetManyReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyReq.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyReq proto.InternalMessageInfo

func (m *GreetManyReq) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetManyRes struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetManyRes) Reset()         { *m = GreetManyRes{} }
func (m *GreetManyRes) String() string { return proto.CompactTextString(m) }
func (*GreetManyRes) ProtoMessage()    {}
func (*GreetManyRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{4}
}

func (m *GreetManyRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetManyRes.Unmarshal(m, b)
}
func (m *GreetManyRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetManyRes.Marshal(b, m, deterministic)
}
func (m *GreetManyRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetManyRes.Merge(m, src)
}
func (m *GreetManyRes) XXX_Size() int {
	return xxx_messageInfo_GreetManyRes.Size(m)
}
func (m *GreetManyRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetManyRes.DiscardUnknown(m)
}

var xxx_messageInfo_GreetManyRes proto.InternalMessageInfo

func (m *GreetManyRes) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetLongReq struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetLongReq) Reset()         { *m = GreetLongReq{} }
func (m *GreetLongReq) String() string { return proto.CompactTextString(m) }
func (*GreetLongReq) ProtoMessage()    {}
func (*GreetLongReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{5}
}

func (m *GreetLongReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetLongReq.Unmarshal(m, b)
}
func (m *GreetLongReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetLongReq.Marshal(b, m, deterministic)
}
func (m *GreetLongReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetLongReq.Merge(m, src)
}
func (m *GreetLongReq) XXX_Size() int {
	return xxx_messageInfo_GreetLongReq.Size(m)
}
func (m *GreetLongReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetLongReq.DiscardUnknown(m)
}

var xxx_messageInfo_GreetLongReq proto.InternalMessageInfo

func (m *GreetLongReq) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetLongRes struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetLongRes) Reset()         { *m = GreetLongRes{} }
func (m *GreetLongRes) String() string { return proto.CompactTextString(m) }
func (*GreetLongRes) ProtoMessage()    {}
func (*GreetLongRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{6}
}

func (m *GreetLongRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetLongRes.Unmarshal(m, b)
}
func (m *GreetLongRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetLongRes.Marshal(b, m, deterministic)
}
func (m *GreetLongRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetLongRes.Merge(m, src)
}
func (m *GreetLongRes) XXX_Size() int {
	return xxx_messageInfo_GreetLongRes.Size(m)
}
func (m *GreetLongRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetLongRes.DiscardUnknown(m)
}

var xxx_messageInfo_GreetLongRes proto.InternalMessageInfo

func (m *GreetLongRes) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetEveryOneReq struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetEveryOneReq) Reset()         { *m = GreetEveryOneReq{} }
func (m *GreetEveryOneReq) String() string { return proto.CompactTextString(m) }
func (*GreetEveryOneReq) ProtoMessage()    {}
func (*GreetEveryOneReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{7}
}

func (m *GreetEveryOneReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEveryOneReq.Unmarshal(m, b)
}
func (m *GreetEveryOneReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEveryOneReq.Marshal(b, m, deterministic)
}
func (m *GreetEveryOneReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEveryOneReq.Merge(m, src)
}
func (m *GreetEveryOneReq) XXX_Size() int {
	return xxx_messageInfo_GreetEveryOneReq.Size(m)
}
func (m *GreetEveryOneReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEveryOneReq.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEveryOneReq proto.InternalMessageInfo

func (m *GreetEveryOneReq) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetEveryOneRes struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetEveryOneRes) Reset()         { *m = GreetEveryOneRes{} }
func (m *GreetEveryOneRes) String() string { return proto.CompactTextString(m) }
func (*GreetEveryOneRes) ProtoMessage()    {}
func (*GreetEveryOneRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{8}
}

func (m *GreetEveryOneRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetEveryOneRes.Unmarshal(m, b)
}
func (m *GreetEveryOneRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetEveryOneRes.Marshal(b, m, deterministic)
}
func (m *GreetEveryOneRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetEveryOneRes.Merge(m, src)
}
func (m *GreetEveryOneRes) XXX_Size() int {
	return xxx_messageInfo_GreetEveryOneRes.Size(m)
}
func (m *GreetEveryOneRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetEveryOneRes.DiscardUnknown(m)
}

var xxx_messageInfo_GreetEveryOneRes proto.InternalMessageInfo

func (m *GreetEveryOneRes) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

type GreetDeadLineReq struct {
	Greeting             *Greeting `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GreetDeadLineReq) Reset()         { *m = GreetDeadLineReq{} }
func (m *GreetDeadLineReq) String() string { return proto.CompactTextString(m) }
func (*GreetDeadLineReq) ProtoMessage()    {}
func (*GreetDeadLineReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{9}
}

func (m *GreetDeadLineReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetDeadLineReq.Unmarshal(m, b)
}
func (m *GreetDeadLineReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetDeadLineReq.Marshal(b, m, deterministic)
}
func (m *GreetDeadLineReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetDeadLineReq.Merge(m, src)
}
func (m *GreetDeadLineReq) XXX_Size() int {
	return xxx_messageInfo_GreetDeadLineReq.Size(m)
}
func (m *GreetDeadLineReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetDeadLineReq.DiscardUnknown(m)
}

var xxx_messageInfo_GreetDeadLineReq proto.InternalMessageInfo

func (m *GreetDeadLineReq) GetGreeting() *Greeting {
	if m != nil {
		return m.Greeting
	}
	return nil
}

type GreetDeadLineRes struct {
	Result               string   `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetDeadLineRes) Reset()         { *m = GreetDeadLineRes{} }
func (m *GreetDeadLineRes) String() string { return proto.CompactTextString(m) }
func (*GreetDeadLineRes) ProtoMessage()    {}
func (*GreetDeadLineRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe6f881da19a2871, []int{10}
}

func (m *GreetDeadLineRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetDeadLineRes.Unmarshal(m, b)
}
func (m *GreetDeadLineRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetDeadLineRes.Marshal(b, m, deterministic)
}
func (m *GreetDeadLineRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetDeadLineRes.Merge(m, src)
}
func (m *GreetDeadLineRes) XXX_Size() int {
	return xxx_messageInfo_GreetDeadLineRes.Size(m)
}
func (m *GreetDeadLineRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetDeadLineRes.DiscardUnknown(m)
}

var xxx_messageInfo_GreetDeadLineRes proto.InternalMessageInfo

func (m *GreetDeadLineRes) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*Greeting)(nil), "greet.Greeting")
	proto.RegisterType((*GreetReq)(nil), "greet.GreetReq")
	proto.RegisterType((*GreetRes)(nil), "greet.GreetRes")
	proto.RegisterType((*GreetManyReq)(nil), "greet.GreetManyReq")
	proto.RegisterType((*GreetManyRes)(nil), "greet.GreetManyRes")
	proto.RegisterType((*GreetLongReq)(nil), "greet.GreetLongReq")
	proto.RegisterType((*GreetLongRes)(nil), "greet.GreetLongRes")
	proto.RegisterType((*GreetEveryOneReq)(nil), "greet.GreetEveryOneReq")
	proto.RegisterType((*GreetEveryOneRes)(nil), "greet.GreetEveryOneRes")
	proto.RegisterType((*GreetDeadLineReq)(nil), "greet.GreetDeadLineReq")
	proto.RegisterType((*GreetDeadLineRes)(nil), "greet.GreetDeadLineRes")
}

func init() { proto.RegisterFile("greet/greetpb/greet.proto", fileDescriptor_fe6f881da19a2871) }

var fileDescriptor_fe6f881da19a2871 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x93, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x93, 0x42, 0x6b, 0x33, 0x2a, 0xea, 0x08, 0xfe, 0x89, 0x08, 0xb2, 0x07, 0x29, 0x16,
	0x6a, 0xa9, 0x07, 0x11, 0x0f, 0x82, 0xa8, 0xbd, 0x54, 0x85, 0x78, 0x10, 0xbc, 0x48, 0xaa, 0x63,
	0x0c, 0xb4, 0x49, 0xbb, 0x1b, 0x0b, 0xfd, 0x7c, 0x7e, 0x31, 0xc9, 0x64, 0x13, 0x13, 0x6d, 0x28,
	0xd5, 0x4b, 0x9b, 0x99, 0x37, 0xf3, 0x7e, 0x30, 0x8f, 0x85, 0x5d, 0x4f, 0x12, 0x45, 0xc7, 0xfc,
	0x3b, 0xea, 0x27, 0xff, 0xad, 0x91, 0x0c, 0xa3, 0x10, 0xab, 0x5c, 0x88, 0x1b, 0xa8, 0x77, 0xe3,
	0x0f, 0x3f, 0xf0, 0x70, 0x1f, 0xe0, 0xcd, 0x97, 0x2a, 0x7a, 0x0e, 0xdc, 0x21, 0xed, 0x98, 0x07,
	0x66, 0xc3, 0x72, 0x2c, 0xee, 0xdc, 0xb9, 0x43, 0xc2, 0x3d, 0xb0, 0x06, 0x6e, 0xaa, 0x56, 0x58,
	0xad, 0xc7, 0x8d, 0x58, 0x14, 0xa7, 0xda, 0xc7, 0xa1, 0x31, 0x36, 0xa1, 0xee, 0x69, 0x4f, 0x76,
	0x59, 0xee, 0xac, 0xb5, 0x12, 0x74, 0x8a, 0x72, 0xb2, 0x01, 0x21, 0xb2, 0x45, 0x85, 0x5b, 0x50,
	0x93, 0xa4, 0x3e, 0x06, 0x91, 0x86, 0xeb, 0x4a, 0x9c, 0xc3, 0x0a, 0xcf, 0xdc, 0xba, 0xc1, 0x74,
	0x61, 0xc0, 0x61, 0x61, 0x79, 0x3e, 0xa4, 0x17, 0x06, 0xde, 0x9f, 0x21, 0xc9, 0x72, 0x39, 0xe4,
	0x02, 0xd6, 0x79, 0xee, 0x7a, 0x42, 0x72, 0x7a, 0x1f, 0xd0, 0xc2, 0xa0, 0xa3, 0x5f, 0x06, 0xf3,
	0x61, 0x57, 0xe4, 0xbe, 0xf6, 0xfc, 0x7f, 0xc0, 0xbe, 0x0d, 0x4a, 0x61, 0x9d, 0xcf, 0x8a, 0x3e,
	0xc1, 0x03, 0xc9, 0x89, 0xff, 0x42, 0xd8, 0x84, 0x2a, 0xd7, 0x58, 0x00, 0x38, 0x34, 0xb6, 0x7f,
	0x34, 0x94, 0x30, 0xf0, 0x0c, 0xac, 0x2c, 0x24, 0xdc, 0xcc, 0xeb, 0x3a, 0x73, 0x7b, 0x46, 0x53,
	0x09, 0xa3, 0x6d, 0x66, 0xab, 0xf1, 0xe9, 0x8b, 0xab, 0x3a, 0x49, 0x7b, 0x46, 0x53, 0x09, 0xa3,
	0x61, 0x62, 0x17, 0x56, 0x0b, 0xc7, 0xc4, 0xed, 0xfc, 0x64, 0x2e, 0x23, 0xbb, 0x44, 0x60, 0x9b,
	0x76, 0x6c, 0xb4, 0xc1, 0xca, 0xa3, 0x1f, 0xbd, 0xa7, 0xc7, 0x2a, 0x9a, 0xe5, 0x32, 0xb0, 0x4b,
	0x04, 0x25, 0x8c, 0x4b, 0xeb, 0x69, 0x49, 0x3f, 0xd6, 0x7e, 0x8d, 0xdf, 0xe9, 0xc9, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0xa9, 0x98, 0xcd, 0x14, 0xc4, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreetServiceClient is the client API for GreetService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreetServiceClient interface {
	Greet(ctx context.Context, in *GreetReq, opts ...grpc.CallOption) (*GreetRes, error)
	GreetMany(ctx context.Context, in *GreetManyReq, opts ...grpc.CallOption) (GreetService_GreetManyClient, error)
	GreetLong(ctx context.Context, opts ...grpc.CallOption) (GreetService_GreetLongClient, error)
	GreetEveryOne(ctx context.Context, opts ...grpc.CallOption) (GreetService_GreetEveryOneClient, error)
	GreetWithDeadLine(ctx context.Context, in *GreetDeadLineReq, opts ...grpc.CallOption) (*GreetDeadLineRes, error)
}

type greetServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetServiceClient(cc *grpc.ClientConn) GreetServiceClient {
	return &greetServiceClient{cc}
}

func (c *greetServiceClient) Greet(ctx context.Context, in *GreetReq, opts ...grpc.CallOption) (*GreetRes, error) {
	out := new(GreetRes)
	err := c.cc.Invoke(ctx, "/greet.GreetService/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetServiceClient) GreetMany(ctx context.Context, in *GreetManyReq, opts ...grpc.CallOption) (GreetService_GreetManyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[0], "/greet.GreetService/GreetMany", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetManyClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GreetService_GreetManyClient interface {
	Recv() (*GreetManyRes, error)
	grpc.ClientStream
}

type greetServiceGreetManyClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetManyClient) Recv() (*GreetManyRes, error) {
	m := new(GreetManyRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) GreetLong(ctx context.Context, opts ...grpc.CallOption) (GreetService_GreetLongClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[1], "/greet.GreetService/GreetLong", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetLongClient{stream}
	return x, nil
}

type GreetService_GreetLongClient interface {
	Send(*GreetLongReq) error
	CloseAndRecv() (*GreetLongRes, error)
	grpc.ClientStream
}

type greetServiceGreetLongClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetLongClient) Send(m *GreetLongReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceGreetLongClient) CloseAndRecv() (*GreetLongRes, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(GreetLongRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) GreetEveryOne(ctx context.Context, opts ...grpc.CallOption) (GreetService_GreetEveryOneClient, error) {
	stream, err := c.cc.NewStream(ctx, &_GreetService_serviceDesc.Streams[2], "/greet.GreetService/GreetEveryOne", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServiceGreetEveryOneClient{stream}
	return x, nil
}

type GreetService_GreetEveryOneClient interface {
	Send(*GreetEveryOneReq) error
	Recv() (*GreetEveryOneRes, error)
	grpc.ClientStream
}

type greetServiceGreetEveryOneClient struct {
	grpc.ClientStream
}

func (x *greetServiceGreetEveryOneClient) Send(m *GreetEveryOneReq) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetServiceGreetEveryOneClient) Recv() (*GreetEveryOneRes, error) {
	m := new(GreetEveryOneRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetServiceClient) GreetWithDeadLine(ctx context.Context, in *GreetDeadLineReq, opts ...grpc.CallOption) (*GreetDeadLineRes, error) {
	out := new(GreetDeadLineRes)
	err := c.cc.Invoke(ctx, "/greet.GreetService/GreetWithDeadLine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreetServiceServer is the server API for GreetService service.
type GreetServiceServer interface {
	Greet(context.Context, *GreetReq) (*GreetRes, error)
	GreetMany(*GreetManyReq, GreetService_GreetManyServer) error
	GreetLong(GreetService_GreetLongServer) error
	GreetEveryOne(GreetService_GreetEveryOneServer) error
	GreetWithDeadLine(context.Context, *GreetDeadLineReq) (*GreetDeadLineRes, error)
}

// UnimplementedGreetServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGreetServiceServer struct {
}

func (*UnimplementedGreetServiceServer) Greet(ctx context.Context, req *GreetReq) (*GreetRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (*UnimplementedGreetServiceServer) GreetMany(req *GreetManyReq, srv GreetService_GreetManyServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetMany not implemented")
}
func (*UnimplementedGreetServiceServer) GreetLong(srv GreetService_GreetLongServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetLong not implemented")
}
func (*UnimplementedGreetServiceServer) GreetEveryOne(srv GreetService_GreetEveryOneServer) error {
	return status.Errorf(codes.Unimplemented, "method GreetEveryOne not implemented")
}
func (*UnimplementedGreetServiceServer) GreetWithDeadLine(ctx context.Context, req *GreetDeadLineReq) (*GreetDeadLineRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GreetWithDeadLine not implemented")
}

func RegisterGreetServiceServer(s *grpc.Server, srv GreetServiceServer) {
	s.RegisterService(&_GreetService_serviceDesc, srv)
}

func _GreetService_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.GreetService/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).Greet(ctx, req.(*GreetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _GreetService_GreetMany_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GreetManyReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServiceServer).GreetMany(m, &greetServiceGreetManyServer{stream})
}

type GreetService_GreetManyServer interface {
	Send(*GreetManyRes) error
	grpc.ServerStream
}

type greetServiceGreetManyServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetManyServer) Send(m *GreetManyRes) error {
	return x.ServerStream.SendMsg(m)
}

func _GreetService_GreetLong_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).GreetLong(&greetServiceGreetLongServer{stream})
}

type GreetService_GreetLongServer interface {
	SendAndClose(*GreetLongRes) error
	Recv() (*GreetLongReq, error)
	grpc.ServerStream
}

type greetServiceGreetLongServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetLongServer) SendAndClose(m *GreetLongRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceGreetLongServer) Recv() (*GreetLongReq, error) {
	m := new(GreetLongReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_GreetEveryOne_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServiceServer).GreetEveryOne(&greetServiceGreetEveryOneServer{stream})
}

type GreetService_GreetEveryOneServer interface {
	Send(*GreetEveryOneRes) error
	Recv() (*GreetEveryOneReq, error)
	grpc.ServerStream
}

type greetServiceGreetEveryOneServer struct {
	grpc.ServerStream
}

func (x *greetServiceGreetEveryOneServer) Send(m *GreetEveryOneRes) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetServiceGreetEveryOneServer) Recv() (*GreetEveryOneReq, error) {
	m := new(GreetEveryOneReq)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _GreetService_GreetWithDeadLine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetDeadLineReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServiceServer).GreetWithDeadLine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greet.GreetService/GreetWithDeadLine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServiceServer).GreetWithDeadLine(ctx, req.(*GreetDeadLineReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GreetService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "greet.GreetService",
	HandlerType: (*GreetServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _GreetService_Greet_Handler,
		},
		{
			MethodName: "GreetWithDeadLine",
			Handler:    _GreetService_GreetWithDeadLine_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetMany",
			Handler:       _GreetService_GreetMany_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GreetLong",
			Handler:       _GreetService_GreetLong_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GreetEveryOne",
			Handler:       _GreetService_GreetEveryOne_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "greet/greetpb/greet.proto",
}
